### ISSUE TITLE
The app fails to query local proxy server because of https only restriction 

### ISSUE THREAD

**Issue by norohind** [paroj/DSub2000#15]
It appears that app tries to use some local proxy-like server (maybe ServerProxy module used exactly for this in the project) and it fails due to https only restriction (I guess regression of 4ecf2020)
```
[04-14 14:36:02.531 6777:6813 E/ImageLoader]
Failed to download from url http://127.0.0.1:4533/share/img/<jwt token>?size=600
javax.net.ssl.SSLException: Only https connections are allowed!
	at github.daneren2005.dsub.service.RESTMusicService.getConnectionDirect(RESTMusicService.java:15)
	at github.daneren2005.dsub.service.RESTMusicService.getConnectionDirect(RESTMusicService.java:11)
	at github.daneren2005.dsub.service.RESTMusicService.getConnection(RESTMusicService.java:4)
	at github.daneren2005.dsub.service.RESTMusicService.getBitmapFromUrl(RESTMusicService.java:13)
	at github.daneren2005.dsub.service.RESTMusicService.getBitmap(RESTMusicService.java:14)
	at github.daneren2005.dsub.service.CachedMusicService.getBitmap(CachedMusicService.java:73)
	at github.daneren2005.dsub.util.ImageLoader$ViewUrlTask.doInBackground(ImageLoader.java:13)
	at github.daneren2005.dsub.util.BackgroundTask$Task.access$300(BackgroundTask.java:24)
	at github.daneren2005.dsub.util.BackgroundTask$TaskRunnable.run(BackgroundTask.java:30)
	at java.lang.Thread.run(Thread.java:923)
```

After couple seconds after it the app appeared to crash, it was playing in background with screen locked and for me, it just stopped playing, when I opened the app it loaded like it wasn't running in background. Beside these two exceptions (they were exactly the same and followed each other with 300 ms interval), I don't have any clue what happened to the app.

**Comment by flyingOwl** [comment]
This sounds like a problem of your server (navidrome?). It seems to return bad URLs for images. You might check if https://github.com/navidrome/navidrome/issues/2552 is what you experience.

**Comment by norohind** [comment]
Indeed it appears to be it. Thanks for pointing out, I was already blaming the app. Now I set the required on navidrome env variable. 
Will reopen issue if problem will show itself again.
Thanks!
